# Generated by Django 4.2.5 on 2023-10-10 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coffee_beans', models.CharField(max_length=200)),
                ('drip_method', models.CharField(max_length=200)),
                ('ground_amount', models.IntegerField(default=0)),
                ('brewing_ratio', models.IntegerField(default=0)),
                ('total_amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drip_pos', models.IntegerField(default=0)),
                ('state', models.CharField(max_length=200)),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiosk.recipe')),
            ],
            options={
                'ordering': ['order_time'],
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=200)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiosk.recipe')),
            ],
        ),
    ]
