# Generated by Django 5.0.3 on 2024-03-07 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=200)),
                ('bean_name', models.CharField(max_length=200)),
                ('pattern', models.CharField(max_length=200)),
                ('water', models.IntegerField(default=0)),
                ('bean_weight', models.IntegerField(default=0)),
                ('rinsing', models.BooleanField(default=True)),
                ('drip', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiosk.recipe'),
        ),
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
