# Generated by Django 5.0.3 on 2024-03-07 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0002_recipe_alter_order_recipe_delete_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='mode',
            field=models.CharField(default='Parameter', max_length=200),
        ),
    ]
