# Generated by Django 5.0.3 on 2024-03-07 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0003_recipe_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_name',
        ),
    ]
